#import "./modules/books/types.gql"
#import "./modules/starships/types.gql"

type Query {
  books: [Book!]!
  book(id: ID!): Book
  starships: [Starship!]!
}

type Mutation {
  addBook(book: BookInput!): Book
  removeBook(id: ID!): Book
  updateBook(id: ID!, book: UpdateBookInput!): Book
}

